# General
name: jag's blog
description: "THANKS GOD. It's Friday."
url: http://jag212.github.io

markdown: redcarpet
highlighter: pygments

paginate: 5
permalink: /:title

# Social share and comments.
disqus-id: jag212
github: jag212
google: +jag212
